FROM quay.io/centos/centos:stream8

RUN dnf -y update && \
    dnf -y install tang clevis jose http-parser socat && \
    dnf clean all

EXPOSE 7500/tcp

COPY root/ /

CMD /bin/socat "TCP6-LISTEN:7500,reuseaddr,fork" "system:'REMOTE_ADDR=\$SOCAT_PEERADDR /usr/libexec/tangd /var/db/tang'"