FROM quay.io/centos/centos:stream9

RUN dnf -y update && \
    dnf -y install curl --allowerasing && \
    dnf -y install tang clevis jose http-parser socat bind-utils iputils procps telnet net-tools wget && \
    dnf clean all

EXPOSE 7500/tcp

COPY root/ /

CMD /bin/socat -d -d "TCP6-LISTEN:7500,reuseaddr,fork" "system:'REMOTE_ADDR=\$SOCAT_PEERADDR /usr/libexec/tangd /var/db/tang' 2>&1"
