FROM quay.io/centos/centos:stream9

RUN dnf -y install dnsmasq bind-utils iputils procps telnet net-tools socat wget && \
    dnf clean all

COPY root/ /

CMD ["dnsmasq", "--keep-in-foreground", "--no-daemon"]
