FROM quay.io/fedora/fedora-coreos:stable

ENTRYPOINT ["/bin/bash"]

RUN set -x; arch=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/'); cat /etc/os-release \
    && rpm-ostree install \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        #https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && ostree container commit

# Replacing nfs-utils-coreos with nfs-utils as some required packages (e.g., libvirt) depend on it: see coreos/fedora-coreos-tracker#572
# Also, installing nfs-utils will leave content in /var. `rm -rf /var/*` is a workaround until the packages are fixed.
RUN rpm-ostree uninstall nfs-utils-coreos && rpm-ostree install nfs-utils && rm -rf /var/* && ostree container commit

RUN set -x; PACKAGES_INSTALL="bridge-utils conntrack-tools curl fping iftop iputils iproute mtr nethogs socat chrony iperf \
                              iperf3 iputils mtr ethtool tftp wget ipmitool gawk targetcli net-tools bind-utils htop ncdu \
                              procps strace iotop subversion git git-lfs gnupg2 lldpd openssl openvpn rsync nmap nmap-ncat zsh \
                              krb5-workstation qemu-kvm qemu-user-static libvirt virt-manager virt-install crypto-policies-scripts \
                              sudo screen telnet unzip util-linux-user ignition lshw tcpdump socat python3-pip man pciutils  \
                              skopeo jq vim neovim inotify-tools firewall-config openvswitch NetworkManager-ovs tree sshpass"; \
    rpm-ostree override remove git-core \
    && rpm-ostree install $PACKAGES_INSTALL \
    && ln -sf /usr/sbin/ovs-vswitchd.dpdk /usr/sbin/ovs-vswitchd \
    && rm -rf /var/* \
    && rpm-ostree cleanup -m \
    && ostree container commit

COPY root/ /

RUN set -x; systemctl preset-all \
    && rpm-ostree ex rebuild \
    && rpm-ostree cleanup -m \
    && ln -sf /usr/bin/podman /usr/bin/docker \
    && echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/99-sysctl.conf \
    && echo "net.ipv6.conf.all.forwarding = 1" >> /etc/sysctl.d/99-sysctl.conf \
    && echo "net.ipv4.ip_unprivileged_port_start = 1" >> /etc/sysctl.d/99-sysctl.conf \
    && echo "PermitRootLogin prohibit-password" >> /etc/ssh/sshd_config.d/90-ssh-root-login.conf \
    && echo -n > /etc/hosts_pool_inventory \
    && echo -n > /etc/hosts_pool_reserved \
    && chown 1000:1000 /etc/hosts_pool_reserved \
    && chmod 600 /etc/ssh/ssh_config.d/*

# Install zsh
RUN HOME=/tmp RUNZSH=no CHSH=no ZSH=/usr/lib/ohmyzsh \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    && set -x \
    && wget -qO /usr/lib/ohmyzsh/custom/kube-ps1.plugin.zsh \
        https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/kube-ps1/kube-ps1.plugin.zsh \
    && mv /usr/share/zsh/*.zsh /usr/lib/ohmyzsh/custom/ \
    && git clone https://github.com/zsh-users/zsh-history-substring-search \
     /usr/lib/ohmyzsh/custom/plugins/zsh-history-substring-search \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
     /usr/lib/ohmyzsh/custom/plugins/zsh-syntax-highlighting \
    && chsh -s /bin/zsh root \
    && echo 'PATH=~/bin:~/.bin:~/.opt/bin:$PATH' >> /etc/zshenv \
    && sed -i 's|^SHELL=.*|SHELL=/usr/bin/zsh|' /etc/default/useradd \
    # ${VARIANT_ID^} is not posix compliant and is not parsed correctly by zsh \
    && sed -i 's/VARIANT_ID^/VARIANT_ID/' /etc/profile.d/toolbox.sh \
    && ostree container commit

ARG TOOLBOX_IMAGE=quay.io/openshifttest/fedora:bm-auto-toolbox
RUN set -x; update-crypto-policies --set legacy --no-reload \
    && echo "image = \"${TOOLBOX_IMAGE}\"" >> /etc/containers/toolbox.conf \
    && ostree container commit
